[project]
name = "local-mcp-server"
version = "0.1.0"
description = "Local MCP server with custom tools"
requires-python = ">=3.10"
dependencies = ["mcp"]

[project.scripts]
start-mcp-server = "server:main"
